#!/usr/bin/with-contenv bash

echo '
**********************************************************
**********************************************************
*                                                        *
*                                                        *
*          This image has been deprecated                *
*                                                        *
*           Use the multi-arch images at                 *
*                                                        *
*             linuxserver/lazylibrarian                  *
*                                                        *
*   https://hub.docker.com/r/linuxserver/lazylibrarian   *
*                                                        *
*   https://github.com/linuxserver/docker-lazylibrarian  *
*                                                        *
*                                                        *
*                                                        *
**********************************************************
**********************************************************'